
---
name: Branch Cleanup
# This workflow is triggered on all closed pull requests.
# However the script does not do anything if a merge was not performed.
on:
  pull_request:
    types: [closed]

env:
  NO_BRANCH_DELETED_EXIT_CODE: 0
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jessfraz/branch-cleanup-action@master
