on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2

name: formatting
jobs:
  check-sorted:
    name: check sorted
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: verify example_test.go
        run: |
          grep "^func " example_test.go | sort -c
